<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Authors>mm7h</Authors>
    <Title>XiaoZhi.Net.Server.Vision</Title>
    <RepositoryUrl>https://github.com/mm7h/XiaoZhi.Net</RepositoryUrl>
    <PackageProjectUrl>https://github.com/mm7h/XiaoZhi.Net</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XiaoZhi.Net.Server.Abstractions\XiaoZhi.Net.Server.Abstractions.csproj" />
    <ProjectReference Include="..\..\XiaoZhi.Net.Server.I18n\XiaoZhi.Net.Server.I18n.csproj" />
    <ProjectReference Include="..\XiaoZhi.Net.Server.Vision.Abstractions\XiaoZhi.Net.Server.Vision.Abstractions.csproj" />
  </ItemGroup>

</Project>
