<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.1</Version>
    <Authors>mm7h</Authors>
    <Title>XiaoZhi.Net.Server.RAG.Qdrant</Title>
    <RepositoryUrl>https://github.com/mm7h/XiaoZhi.Net</RepositoryUrl>
    <PackageProjectUrl>https://github.com/mm7h/XiaoZhi.Net</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Qdrant.Client" Version="1.18.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XiaoZhi.Net.Server.Abstractions\XiaoZhi.Net.Server.Abstractions.csproj" />
    <ProjectReference Include="..\XiaoZhi.Net.Server.RAG.Abstractions\XiaoZhi.Net.Server.RAG.Abstractions.csproj" />
  </ItemGroup>
</Project>
