<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="Globals">
        <SccProjectName>SAK</SccProjectName>
        <SccProvider>SAK</SccProvider>
        <SccAuxPath>SAK</SccAuxPath>
        <SccLocalPath>SAK</SccLocalPath>
    </PropertyGroup>
    <PropertyGroup>
        <TargetFramework>net8</TargetFramework>
		<LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ApplicationIcon>robot.ico</ApplicationIcon>
        <Version>0.0.1</Version>
        <Authors>mm7h</Authors>
        <Title>XiaoZhi.Net.Server</Title>
        <PackageIcon />
        <Description>用C#编写的xiaozhi-esp32服务端，帮助您快速搭建ESP32设备控制服务器。
Dotnet backend service for xiaozhi-esp32, helps you quickly build an ESP32 device control server.</Description>
        <RepositoryUrl>https://github.com/mm7h/XiaoZhi.Net</RepositoryUrl>
        <PackageProjectUrl>https://github.com/mm7h/XiaoZhi.Net</PackageProjectUrl>
    </PropertyGroup>
    <ItemGroup>
      <Content Include="robot.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Concentus" Version="2.2.2" />
        <PackageReference Include="Flurl.Http" Version="4.0.2" />
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool.DependencyInjection" Version="9.8.0" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
        <PackageReference Include="Microsoft.SemanticKernel" Version="1.60.0" />
        <PackageReference Include="ModelContextProtocol-SemanticKernel" Version="0.3.0-preview-01" />
        <PackageReference Include="org.k2fsa.sherpa.onnx" Version="1.12.7" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SuperSocket.WebSocket.Server" Version="2.0.2" />
        <PackageReference Include="Websocket.Client" Version="5.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\XiaoZhi.Net.Server.Abstractions\XiaoZhi.Net.Server.Abstractions.csproj" />
      <ProjectReference Include="..\XiaoZhi.Net.Server.FFmpeg.Abstractions\XiaoZhi.Net.Server.FFmpeg.Abstractions.csproj" />
      <ProjectReference Include="..\XiaoZhi.Net.Server.FFmpeg\XiaoZhi.Net.Server.FFmpeg.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Server\Providers\AudioMixer\" />
    </ItemGroup>

</Project>
